### ISSUE TITLE
url for checkpoint

### ISSUE THREAD

**Issue by baogenduan** [AlphaGenX/TamGen#1]
Hi,
 
   Would you like to provide a link to checkpoint. Thanks in advance.

**Comment by zemanet2020** [comment]
Model is not available.
https://microsoftapc-my.sharepoint.com/:f:/g/personal/v-kehanwu_microsoft_com/EipAXgQfu6lPm1y2OP1ZUyEBsqQbPZ7aukhJ8_hgUej0yw?e=fE9G6h
Please fix the link.

**Comment by xyc1207** [comment]
The checkpoint can be found in https://doi.org/10.5281/zenodo.13751391. Please download checkpoints.zip & gpt_model.zip and uncompress them. After that, you will get two folders: checkpoints and gpt_model. Please place them under the folder TamGen/. 

https://github.com/SigmaGenX/TamGen?tab=readme-ov-file#model
