### ISSUE TITLE
Question about Fig 2 (b) plot

### ISSUE THREAD

**Issue by vincrichard** [AlphaGenX/TamGen#2]
Hello authors, and thank you for your work !

I would like to reproduce the plot display in Fig2 (b). I tried with the test data shared by Target diff [here](https://drive.google.com/drive/folders/19imu-mlwrjnQhgbXpwsLgA17s1Rv70YS), however I did not manage to generate a matching plot. 

Could you explain what type of data you used ? The plot is the average docking scores against SAS, but which average are we talking about ? Average of the already average score on the pocket, on all 10k molecule generated ?

If you still have the code for the generation of this graph, and you can share it, it would be wonderful. 

Best regards

**Comment by xyc1207** [comment]
Hi vincrichard ,

Thanks for your interests. We provide the data in `crossdocked_results.zip` of the repo https://zenodo.org/records/13751391.

**Comment by vincrichard** [comment]
Hello @xyc1207,
Thank you for sharing the information, I could find the script and reproduce the plot. 
All the best.
